---
title: "lab07_assignment"
format: html
editor: visual
---

## Load Libraries

```{r}
library("tidyverse")
library("broom")
library("cowplot")
```

## Load data

We will in this mini-report a biopsy dataset from the university of Wisconsin Hospitals. A set of 699 patients and a sample from nine variables with a scoring of 1-10 seen in the figure below, along with the outcome of the tumor.

```{r}
#| message: false
biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
biopsy |> glimpse(width = 5)
```

## Data Wrangle

```{r}
pca_fit <- biopsy |>
  select(where(is.numeric)) |>
  prcomp(scale = TRUE)
```

```{r}
pca_fit_score <- pca_fit |>
  augment(biopsy)
```

## Analysis

## PC coordinates

```{r}
plot_pc <- function(pc_x, pc_y) {
  ggplot(pca_fit_score, aes_string(x = pc_x, y = pc_y, color = "outcome")) +
    geom_point(size = 1.5, alpha = 0.8) +
    scale_color_manual(
      values = c(malignant = "salmon", benign = "skyblue")
    ) +
    theme_half_open(12) + background_grid() +
    labs(title = paste(pc_x, "vs", pc_y),
         x = paste(pc_x),
         y = paste(pc_y),
         color = "Tumor outcome")
}
  
```

```{r}
pca_fit |>
  augment(biopsy) |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "salmon", benign = "skyblue")
  ) +
  theme_half_open(12) + background_grid() +
  labs(title = "PCA Space",
       x = "Principal component 1", 
       y = "Principal component 2",
       color = "Tumor outcome")
```

```{r}
plot_pc(".fittedPC1", ".fittedPC2")
```
